### ISSUE TITLE
Make the tribe NFT contract

### ISSUE THREAD

**Issue by fricoben** [starknet-id/tribe_nft#1]
### Tribe NFT contract

Ici notre but est d'avoir une collection NFT d'équipement de la tribe, ces équipements auront plusieurs level. 

Donc tu aurais un collier par exemple avec le collier level 1 qui a sa propre image, le level 2 et 3 pareil.

Exemples des colliers: 
![tribeSoldier](https://user-images.githubusercontent.com/78437165/230622515-4a945e5d-7d0b-4608-9ec8-984a418665c1.png)

![tribeOfficer](https://user-images.githubusercontent.com/78437165/230622492-3142ab96-f613-4c12-9edf-bf1ed56d3f90.png)

![tribeChef](https://user-images.githubusercontent.com/78437165/230622469-2cbb98ed-6026-4d8d-b816-e9a8f3d7a665.png)

**Comment by Th0rgal** [comment]
L’objectif est de représenter différentes catégories de NFT au sein du même contrat de la manière la plus simple possible.Pour cela, on utilise l'ID du token pour déterminer le type de NFT. On divise l'ID par 100 (cela représente le nombre de catégories possibles avec de la marge), et on récupère le reste. Ce reste permet d'identifier le type de NFT et d'appliquer une logique spécifique pour chaque type lors du minting.

Dans la fonction de minting, on prend en condition le reste pour vérifier le type de NFT et appliquer des conditions spécifiques en fonction de ce type. Par exemple (pseudo code):
```py
mint(id):
  reste = id % 100
  if reste == 0: # sac
    assert peut_mint_un_sac
  elif reste == 1: # cape
    ...
  else:
    assert 1 == 0
```
De la même manière, pour la fonction get_token_uri, on peut renvoyer une URI différente en fonction du type de l'id :
```py
get_token_uri(id):
  reste = id % 100
  if reste == 0: # sac
    return url_image_sac
  elif reste == 1: # cape
    return url_image_cape
  ...
  ```
